included:
    - Sources
    - Tests
line_length:
    warning: 130
    error: 200

identifier_name:
    max_length:
        warning: 45
        error: 60
    min_length:
        warning: 1

type_name:
    max_length:
        warning: 45
        error: 60
    min_length:
        warning: 1
disabled_rules:
    - trailing_comma
    - discouraged_direct_init
    - multiple_closures_with_trailing_closure
    - force_cast
    - force_try
    - large_tuple
opt_in_rules: # some rules are only opt-in

  # Rules:: https://realm.github.io/SwiftLint/rule-directory.html
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - discarded_notification_center_observer
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - implicit_getter
  - is_disjoint
  - joined_default_parameter
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - lower_acl_than_parent
  - mark
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - unneeded_break_in_switch
  - unused_control_flow_label
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace  
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition
  - reduce_boolean
  - nsobject_prefer_isequal
  - unowned_variable_capture
  - duplicate_enum_cases
  - legacy_multiple